set(TEST_LIST
    functional/00_main
    functional/01_var_defn2
    functional/02_var_defn3
    functional/03_arr_defn2
    functional/06_const_var_defn2
    functional/07_const_var_defn3
    functional/09_func_defn
    functional/10_var_defn_func
    functional/11_add2
    functional/12_addc
    functional/14_subc
    functional/15_mul
    functional/16_mulc
    functional/17_div
    functional/18_divc
    functional/19_mod
    functional/35_op_priority1
    functional/36_op_priority2
    functional/37_op_priority3
    functional/42_empty_stmt
    functional/45_comment1
    functional/46_hex_defn
    functional/47_hex_oct_add
    h_functional/00_comment2
    h_functional/01_multiple_returns
    h_functional/05_param_name
    h_functional/06_func_name
    h_functional/08_global_arr_init
)

set(FAIL_TEST_LIST
    functional/04_arr_defn3
    functional/05_arr_defn4
    functional/08_const_array_defn
    functional/13_sub2
    functional/20_rem
    functional/21_if_test2
    functional/22_if_test3
    functional/23_if_test4
    functional/24_if_test5
    functional/25_while_if
    functional/26_while_test1
    functional/27_while_test2
    functional/28_while_test3
    # functional/29_break // succeeds in release
    # functional/30_continue // causes inf loop in release
    functional/31_while_if_test1
    functional/32_while_if_test2
    functional/33_while_if_test3
    functional/34_arr_expr_len
    functional/38_op_priority4
    functional/39_op_priority5
    functional/40_unary_op
    functional/41_unary_op2
    # functional/43_logi_assign // succeeds in release
    # functional/44_stmt_expr // causes inf loop in release
    functional/48_assign_complex_expr
    functional/49_if_complex_expr
    functional/50_short_circuit
    functional/51_short_circuit3
    functional/52_scope
    # functional/53_scope2 // causes inf loop in release
    functional/54_hidden_var
    functional/55_sort_test1
    functional/56_sort_test2
    functional/57_sort_test3
    functional/58_sort_test4
    functional/59_sort_test5
    functional/60_sort_test6
    functional/61_sort_test7
    functional/62_percolation
    functional/63_big_int_mul
    functional/64_calculator
    functional/65_color
    functional/66_exgcd
    functional/67_reverse_output
    functional/68_brainfk
    functional/69_expr_eval
    functional/70_dijkstra
    functional/71_full_conn
    functional/72_hanoi
    functional/73_int_io
    functional/74_kmp
    functional/75_max_flow
    functional/76_n_queens
    functional/77_substr
    functional/78_side_effect
    functional/79_var_name
    functional/80_chaos_token
    functional/81_skip_spaces
    functional/82_long_func
    functional/83_long_array
    functional/84_long_array2
    functional/85_long_code
    # functional/86_long_code2 // causes stack overflow
    functional/87_many_params
    functional/88_many_params2
    functional/89_many_globals
    functional/90_many_locals
    # functional/91_many_locals2 // causes inf loop in release
    functional/92_register_alloc
    functional/93_nested_calls
    functional/94_nested_loops
    functional/95_float
    functional/96_matrix_add
    functional/97_matrix_sub
    functional/98_matrix_mul
    functional/99_matrix_tran
    h_functional/02_ret_in_block
    h_functional/03_branch
    h_functional/04_break_continue
    h_functional/07_arr_init_nd
    h_functional/09_BFS
    h_functional/10_DFS
    h_functional/11_BST
    h_functional/12_DSU
    h_functional/13_LCA
    h_functional/14_dp
    h_functional/15_graph_coloring
    h_functional/16_k_smallest
    h_functional/17_maximal_clique
    h_functional/18_prim
    h_functional/19_search
    h_functional/20_sort
    h_functional/21_union_find
    h_functional/22_matrix_multiply
    h_functional/23_json
    h_functional/24_array_only
    h_functional/25_scope3
    h_functional/26_scope4
    # h_functional/27_scope5 // causes inf loop
    h_functional/28_side_effect2
    h_functional/29_long_line
    h_functional/30_many_dimensions
    h_functional/31_many_indirections
    # h_functional/32_many_params3 // causes inf loop
    # h_functional/33_multi_branch // causes inf loop
    h_functional/34_multi_loop
    h_functional/35_math
    h_functional/36_rotate
    h_functional/37_dct
    h_functional/38_light2d
    h_functional/39_fp_params
)
