#include "MIROpcodes.h"
#include "MachineInst.h"

#include "Utils/Utils.h"

#include <string_view>

namespace Balance {

// ai-generated
namespace {
struct MIRInstrInfo {
    const char *asmstring;
    bool isControlTransfer;
    int numDefs;
    int numUses;
    int numOperands;
    bool isActualInst = true;
};

static const MIRInstrInfo MIRInstructionDB[] = {
    // cti - control transfer instruction (bb terminator)
    // asm-string, is-cti, num-defs, num-uses, num-operands
    { "G_ADD",         false, 1, 2, 3 },
    { "G_SUB",         false, 1, 2, 3 },
    { "G_MUL",         false, 1, 2, 3 },
    { "G_AND",         false, 1, 2, 3 },
    { "G_OR",          false, 1, 2, 3 },
    { "G_XOR",         false, 1, 2, 3 },
    { "G_SHL",         false, 1, 2, 3 },
    { "G_LSHR",        false, 1, 2, 3 },
    { "G_ASHR",        false, 1, 2, 3 },
    { "G_LOAD",        false, 1, 1, 2 },
    { "G_STORE",       false, 0, 2, 2 },
    { "G_CONSTANT",    false, 1, 0, 1 },
    { "G_FRAME_INDEX", false, 1, 0, 1 },
    { "G_BR",          true,  0, 0, 1 },
    { "G_BRCOND",      true,  0, 1, 2 },
    { "LUI",           false, 1, 0, 2 },
    { "AUIPC",         false, 1, 0, 2 },
    { "ADDI",          false, 1, 1, 3 },
    { "SLTI",          false, 1, 1, 3 },
    { "SLTIU",         false, 1, 1, 3 },
    { "XORI",          false, 1, 1, 3 },
    { "ORI",           false, 1, 1, 3 },
    { "ANDI",          false, 1, 1, 3 },
    { "SLLI",          false, 1, 1, 3 },
    { "SRLI",          false, 1, 1, 3 },
    { "SRAI",          false, 1, 1, 3 },
    { "ADD",           false, 1, 2, 3 },
    { "SUB",           false, 1, 2, 3 },
    { "SLL",           false, 1, 2, 3 },
    { "SLT",           false, 1, 2, 3 },
    { "SLTU",          false, 1, 2, 3 },
    { "XOR",           false, 1, 2, 3 },
    { "SRL",           false, 1, 2, 3 },
    { "SRA",           false, 1, 2, 3 },
    { "OR",            false, 1, 2, 3 },
    { "AND",           false, 1, 2, 3 },
    { "ADDIW",         false, 1, 1, 3 },
    { "SLLIW",         false, 1, 1, 3 },
    { "SRLIW",         false, 1, 1, 3 },
    { "SRAIW",         false, 1, 1, 3 },
    { "ADDW",          false, 1, 2, 3 },
    { "SUBW",          false, 1, 2, 3 },
    { "SLLW",          false, 1, 2, 3 },
    { "SRLW",          false, 1, 2, 3 },
    { "SRAW",          false, 1, 2, 3 },
    { "LB",            false, 1, 1, 3 },
    { "LH",            false, 1, 1, 3 },
    { "LW",            false, 1, 1, 3 },
    { "LD",            false, 1, 1, 3 },
    { "LBU",           false, 1, 1, 3 },
    { "LHU",           false, 1, 1, 3 },
    { "LWU",           false, 1, 1, 3 },
    { "SB",            false, 0, 2, 3 },
    { "SH",            false, 0, 2, 3 },
    { "SW",            false, 0, 2, 3 },
    { "SD",            false, 0, 2, 3 },
    { "JAL",           true,  1, 0, 2 },
    { "JALR",          true,  1, 1, 3 },
    { "BEQ",           true,  0, 2, 3 },
    { "BNE",           true,  0, 2, 3 },
    { "BLT",           true,  0, 2, 3 },
    { "BGE",           true,  0, 2, 3 },
    { "BLTU",          true,  0, 2, 3 },
    { "BGEU",          true,  0, 2, 3 },
    { "ECALL",         false, 0, 0, 0 },
    { "EBREAK",        false, 0, 0, 0 },
    { "FENCE",         false, 0, 0, 0 },
    { "FENCE_I",       false, 0, 0, 0 },
    { "CSRRW",         false, 1, 1, 3 },
    { "CSRRS",         false, 1, 1, 3 },
    { "CSRRC",         false, 1, 1, 3 },
    { "CSRRWI",        false, 1, 0, 3 },
    { "CSRRSI",        false, 1, 0, 3 },
    { "CSRRCI",        false, 1, 0, 3 },
    { "MUL",           false, 1, 2, 3 },
    { "MULH",          false, 1, 2, 3 },
    { "MULHSU",        false, 1, 2, 3 },
    { "MULHU",         false, 1, 2, 3 },
    { "DIV",           false, 1, 2, 3 },
    { "DIVU",          false, 1, 2, 3 },
    { "REM",           false, 1, 2, 3 },
    { "REMU",          false, 1, 2, 3 },
    { "MULW",          false, 1, 2, 3 },
    { "DIVW",          false, 1, 2, 3 },
    { "DIVUW",         false, 1, 2, 3 },
    { "REMW",          false, 1, 2, 3 },
    { "REMUW",         false, 1, 2, 3 },
    { "LR_W",          false, 1, 1, 2 },
    { "SC_W",          false, 1, 2, 3 },
    { "AMOSWAP_W",     false, 1, 2, 3 },
    { "AMOADD_W",      false, 1, 2, 3 },
    { "AMOXOR_W",      false, 1, 2, 3 },
    { "AMOAND_W",      false, 1, 2, 3 },
    { "AMOOR_W",       false, 1, 2, 3 },
    { "AMOMIN_W",      false, 1, 2, 3 },
    { "AMOMAX_W",      false, 1, 2, 3 },
    { "AMOMINU_W",     false, 1, 2, 3 },
    { "AMOMAXU_W",     false, 1, 2, 3 },
    { "LR_D",          false, 1, 1, 2 },
    { "SC_D",          false, 1, 2, 3 },
    { "AMOSWAP_D",     false, 1, 2, 3 },
    { "AMOADD_D",      false, 1, 2, 3 },
    { "AMOXOR_D",      false, 1, 2, 3 },
    { "AMOAND_D",      false, 1, 2, 3 },
    { "AMOOR_D",       false, 1, 2, 3 },
    { "AMOMIN_D",      false, 1, 2, 3 },
    { "AMOMAX_D",      false, 1, 2, 3 },
    { "AMOMINU_D",     false, 1, 2, 3 },
    { "AMOMAXU_D",     false, 1, 2, 3 },
    { "FLW",           false, 1, 1, 3 },
    { "FSW",           false, 0, 2, 3 },
    { "FMADD_S",       false, 1, 3, 4 },
    { "FMSUB_S",       false, 1, 3, 4 },
    { "FNMSUB_S",      false, 1, 3, 4 },
    { "FNMADD_S",      false, 1, 3, 4 },
    { "FADD_S",        false, 1, 2, 3 },
    { "FSUB_S",        false, 1, 2, 3 },
    { "FMUL_S",        false, 1, 2, 3 },
    { "FDIV_S",        false, 1, 2, 3 },
    { "FSQRT_S",       false, 1, 1, 2 },
    { "FSGNJ_S",       false, 1, 2, 3 },
    { "FSGNJN_S",      false, 1, 2, 3 },
    { "FSGNJX_S",      false, 1, 2, 3 },
    { "FMIN_S",        false, 1, 2, 3 },
    { "FMAX_S",        false, 1, 2, 3 },
    { "FCVT_W_S",      false, 1, 1, 2 },
    { "FCVT_WU_S",     false, 1, 1, 2 },
    { "FCVT_S_W",      false, 1, 1, 2 },
    { "FCVT_S_WU",     false, 1, 1, 2 },
    { "FMV_X_W",       false, 1, 1, 2 },
    { "FMV_W_X",       false, 1, 1, 2 },
    { "FEQ_S",         false, 1, 2, 3 },
    { "FLT_S",         false, 1, 2, 3 },
    { "FLE_S",         false, 1, 2, 3 },
    { "FCLASS_S",      false, 1, 1, 2 },
    { "FCVT_L_S",      false, 1, 1, 2 },
    { "FCVT_LU_S",     false, 1, 1, 2 },
    { "FCVT_S_L",      false, 1, 1, 2 },
    { "FCVT_S_LU",     false, 1, 1, 2 },
    { "FLD",           false, 1, 1, 3 },
    { "FSD",           false, 0, 2, 3 },
    { "FMADD_D",       false, 1, 3, 4 },
    { "FMSUB_D",       false, 1, 3, 4 },
    { "FNMSUB_D",      false, 1, 3, 4 },
    { "FNMADD_D",      false, 1, 3, 4 },
    { "FADD_D",        false, 1, 2, 3 },
    { "FSUB_D",        false, 1, 2, 3 },
    { "FMUL_D",        false, 1, 2, 3 },
    { "FDIV_D",        false, 1, 2, 3 },
    { "FSQRT_D",       false, 1, 1, 2 },
    { "FSGNJ_D",       false, 1, 2, 3 },
    { "FSGNJN_D",      false, 1, 2, 3 },
    { "FSGNJX_D",      false, 1, 2, 3 },
    { "FMIN_D",        false, 1, 2, 3 },
    { "FMAX_D",        false, 1, 2, 3 },
    { "FCVT_S_D",      false, 1, 1, 2 },
    { "FCVT_D_S",      false, 1, 1, 2 },
    { "FEQ_D",         false, 1, 2, 3 },
    { "FLT_D",         false, 1, 2, 3 },
    { "FLE_D",         false, 1, 2, 3 },
    { "FCLASS_D",      false, 1, 1, 2 },
    { "FCVT_W_D",      false, 1, 1, 2 },
    { "FCVT_WU_D",     false, 1, 1, 2 },
    { "FCVT_D_W",      false, 1, 1, 2 },
    { "FCVT_D_WU",     false, 1, 1, 2 },
    { "FCVT_L_D",      false, 1, 1, 2 },
    { "FCVT_LU_D",     false, 1, 1, 2 },
    { "FMV_X_D",       false, 1, 1, 2 },
    { "FCVT_D_L",      false, 1, 1, 2 },
    { "FCVT_D_LU",     false, 1, 1, 2 },
    { "FMV_D_X",       false, 1, 1, 2 },
    { "C_ADDI4SPN",    false, 1, 1, 2 },
    { "C_FLD",         false, 1, 1, 2 },
    { "C_LW",          false, 1, 1, 2 },
    { "C_LD",          false, 1, 1, 2 },
    { "C_FSD",         false, 0, 2, 2 },
    { "C_SW",          false, 0, 2, 2 },
    { "C_SD",          false, 0, 2, 2 },
    { "C_NOP",         false, 0, 0, 0 },
    { "C_ADDI",        false, 1, 1, 2 },
    { "C_ADDIW",       false, 1, 1, 2 },
    { "C_LI",          false, 1, 0, 1 },
    { "C_ADDI16SP",    false, 1, 1, 2 },
    { "C_LUI",         false, 1, 0, 1 },
    { "C_SRLI",        false, 1, 1, 2 },
    { "C_SRAI",        false, 1, 1, 2 },
    { "C_ANDI",        false, 1, 1, 2 },
    { "C_SUB",         false, 1, 2, 2 },
    { "C_XOR",         false, 1, 2, 2 },
    { "C_OR",          false, 1, 2, 2 },
    { "C_AND",         false, 1, 2, 2 },
    { "C_SUBW",        false, 1, 2, 2 },
    { "C_ADDW",        false, 1, 2, 2 },
    { "C_J",           true,  0, 0, 1 },
    { "C_BEQZ",        true,  0, 1, 2 },
    { "C_BNEZ",        true,  0, 1, 2 },
    { "C_SLLI",        false, 1, 1, 2 },
    { "C_FLDSP",       false, 1, 1, 2 },
    { "C_LWSP",        false, 1, 1, 2 },
    { "C_LDSP",        false, 1, 1, 2 },
    { "C_JR",          true,  0, 1, 1 },
    { "C_MV",          false, 1, 1, 2 },
    { "C_EBREAK",      false, 0, 0, 0 },
    { "C_JALR",        true,  1, 1, 1 },
    { "C_ADD",         false, 1, 2, 2 },
    { "C_FSDSP",       false, 0, 2, 2 },
    { "C_SWSP",        false, 0, 2, 2 },
    { "C_SDSP",        false, 0, 2, 2 },
    { "PHI",           false, 1, -1, -1, false },
};
}

bool isControlTransferInst(const MachineInst &MI) {
    return MIRInstructionDB[MI.getOpcode()].isControlTransfer;
}

std::string_view getInstNameByOpcode(RISCVOpcode Opcode) {
    if (Opcode >= G_ADD && Opcode <= C_SDSP) {
        return MIRInstructionDB[Opcode].asmstring;
    }
    unreachable("Unknown RISCVOpcode");
    return "";
}

unsigned getNumDefs(RISCVOpcode Opcode) {
    if (Opcode >= G_ADD && Opcode <= C_SDSP) {
        return MIRInstructionDB[Opcode].numDefs;
    }
    unreachable("Unknown RISCVOpcode");
    return 0;
}

} // namespace Balance
