name: Mirror to GitLab

on:
  push:
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and mirror
        run: |
          git clone --bare https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}.git

          git push https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.eduxiji.net/T2026000002012235/compiler2026-balance.git main
          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.eduxiji.net/T2026000002012235/compiler2026-balance.git
