name: build

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build-and-all-tests:
        name: "All tests ubuntu-latest ${{ matrix.compiler }} (${{ matrix.build_type }}${{ matrix.sanitizers != '' && ' with sanitizers' || '' }})"
        runs-on: ubuntu-latest
        container: docker.io/ralex2304/balance-ubuntu-ci:v1.0

        strategy:
            fail-fast: false
            matrix:
                build_type: [Release, Debug]
                compiler: [gcc, clang]
                sanitizers: ["address,undefined", ""]
                include:
                - compiler: gcc
                  cc: gcc
                  cxx: g++

                - compiler: clang
                  cc: clang
                  cxx: clang++

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Run Cmake
              run: >
                cmake -B ./build
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
                -DCMAKE_C_COMPILER=${{matrix.cc}}
                -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
                -DUSE_SANITIZER='${{matrix.sanitizers}}'
                -DBUILD_UNIT_TESTS=ON
                -DBUILD_END2END_TESTS=ON
                ${{matrix.generator}}

            - name: Build
              run: cmake --build ./build --config ${{matrix.build_type}}

            - name: Run tests
              run: ctest --test-dir ./build -C ${{matrix.build_type}} --output-on-failure --parallel

            - name: Upload tests
              uses: actions/upload-artifact@v7
              with:
                name: "all_tests_ubuntu_latest_${{matrix.compiler}}_${{matrix.build_type}}${{matrix.sanitizers != '' && '_asan' || ''}}"
                path: |
                  build/tests/functional/
                  build/tests/h_functional/
                  build/tests/performance/
                if-no-files-found: error

    build-and-unit-tests:
        name: "Unit tests ${{ matrix.os }} ${{ matrix.compiler }} (${{ matrix.build_type }}${{ matrix.sanitizers != '' && ' with sanitizers' || '' }})"
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, macos-latest]
                build_type: [Release, Debug]
                compiler: [gcc, clang]
                sanitizers: ["address,undefined", ""]
                include:
                - compiler: gcc
                  cc: gcc
                  cxx: g++

                - compiler: clang
                  cc: clang
                  cxx: clang++

                - os: windows-latest
                  generator: -G "MinGW Makefiles"

                - os: windows-latest
                  build_type: Release
                  compiler: msvc
                  cc: cl
                  cxx: cl

                - os: windows-latest
                  build_type: Debug
                  compiler: msvc
                  cc: cl
                  cxx: cl

                exclude:
                - os: windows-latest
                  sanitizers: "address,undefined"
                - os: macos-latest
                  compiler: gcc

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: MacOS packages installation
              if: ${{ matrix.os == 'macos-latest' }}
              run: |
                  brew untap aws/tap
                  brew update
                  brew install automake texinfo

            - name: Run Cmake
              run: >
                cmake -B ./build
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
                -DCMAKE_C_COMPILER=${{matrix.cc}}
                -DCMAKE_CXX_COMPILER=${{matrix.cxx}}
                -DUSE_SANITIZER='${{matrix.sanitizers}}'
                -DBUILD_UNIT_TESTS=ON
                -DBUILD_END2END_TESTS=OFF
                ${{matrix.generator}}

            - name: Build
              run: cmake --build ./build --config ${{matrix.build_type}}

            - name: Run unit tests
              run: ctest --test-dir ./build -C ${{matrix.build_type}} --output-on-failure --parallel

